### PR TITLE
docs: Improve code examples

### PR DESCRIPTION
**Pull request by coalooball**
See https://github.com/duesee/imap-codec/issues/393

### CODE REVIEW

**Comment by coalooball** [comment]
Also see https://github.com/duesee/imap-codec/issues/394

**Comment by duesee** [comment]
Hehe, I was just about to merge because I overlooked https://github.com/duesee/imap-codec/pull/397/files#diff-cfcb5beb66760b7d974ea036d027714665a3c57f72ca940df6dcdd3e138a1d69R24-R32 :D I think it should be enough to remove this? Same with https://github.com/duesee/imap-codec/pull/397/files#diff-cfcb5beb66760b7d974ea036d027714665a3c57f72ca940df6dcdd3e138a1d69R65-R72?

**Comment by duesee** [comment]
Oh, btw @coalooball: Was this your first PR on GitHub? I feel honored! :D Congratz 🎉

**Comment by coalooball** [comment]
Haha, this is my first PR, and I'm pretty excited about it. Thank you for your blessings, @duesee! I hope I can become as awesome as you, contributing real-code PRs to `imap-codec`.

**Pull request merged**
