### PR TITLE
refactor: Refactor examples

### PR DESCRIPTION
**Pull request by jakoschiko**
As a preparation for the `Fragmentizer` support in Python I want to refactor the existing examples.

After this PR there exists the following examples:

- `fragmentizer.rs`
  - Demonstrates the features of the `Fragmentizer`
  - Already exists
- `client.rs`
  - Demonstrates how a client can be implemented using `Fragmentizer`, `GreetingCodec` and `ResponseCodec`.
  - Reimplements `imap-next`
  - Added by this PR
- `server.rs`
  - Demonstrates how a server can be implemented using `Fragmentizer`, `CommandCodec`, `AuthenticateDataCodec` and `IdleDoneCodec`.
  - Reimplements `imap-next`
  - Added by this PR

The following examples will be removed:
- `fragmentizer_client.rs`
- `fragmentizer_server.rs`
- `parse_greeting.rs`
- `parse_response.rs`
- `parse_command.rs`

### CODE REVIEW

**Comment by jakoschiko** [comment]
The fuzz check failed in the CI due to #590.

**Comment by duesee** [comment]
Any idea how to fix? We could slap a ignore on the lint and create an issue. I can then take a look later so we don't block on this.

**Comment by jakoschiko** [comment]
Just ignore it and wait for https://github.com/rust-lang/rust/pull/129103 getting merged.

**Review by duesee — APPROVED** [review]
Boooring, everything works :P

**Pull request merged**
