### PR TITLE
Exposed a bunch of parse functions to the public API

### PR DESCRIPTION
**Pull request by FelixPodint**
For issue #15 
Exposed some parsing functions from `mod parse`.
Left `crate::parse::core` untouched. Not sure what is useful in `core` for most users.
Also couldn't export some functions that used non-public types, such as `AStringRef`.

### CODE REVIEW

**Comment by duesee** [comment]
Thanks! I will have to learn what `#[doc(inline)]` does and try to check if everything is exported.

In the meantime, could you run `cargo fmt --config imports_granularity=Crate,group_imports=StdExternalCrate`, `git --amend`, and force push?

I will try to review it today. Have you tried to use this version in your email server, i.e., in `Cargo.toml` `imap_codec = { path = "..." }`, and see if you like it that way?

I am asking, because I thought about exposing all parsers directly on the first level of `internal::*`. The reason is that people will likely read the IMAP RFC and wonder if they could use a specific rule. However, this will make `parse` and `internal` go out of sync. Not sure what is the best solution.

**Comment by FelixPodint** [comment]
> could you run cargo fmt --config imports_granularity=Crate,group_imports=StdExternalCrate

This command didn't work, but after changing to nightly and creating `rustfmt.toml` file simple cargo fmt worked. Is it ok?

> Have you tried to use this version in your email server

Yes, currently using local clone.

> and see if you like it that way?

Don't know yet. Everything still feels like a mess (on my end :P), will see...
```
// Little example:
FetchAttribute::Envelope => {
    let envelope_bytes = self.db.envelope(
        &self.user,
        mailbox,
        seq_or_uid.get() as usize,
        uid,
    )?;
    let envelope = match imap_codec::internal::envelope(&envelope_bytes) {
        Ok((remaining, envelope)) => {
            if remaining.is_empty() {
                envelope
            } else {
                return Err(anyhow!(
                    "Some bytes remained after parsing Envelope"
                ));
            }
        }
        Err(e) => {
            return Err(anyhow!(
                "Command parsing error: {}",
                e.map(|e| e.code)
            ));
        }
    };
    rez.push(FetchAttributeValue::Envelope(envelope));
}
```
> I am wondering if we should expose all parsers directly on the first level of `internal::*`.

No, there should be some structure to them.

>  However, this will make `parse` and `internal` go out of sync. Not sure what is the best solution.

Agree, this is why I was thinking about `Decode` trait. Implement it for all types, then appropriate, and don't expose `parser` to public API.

**Comment by FelixPodint** [comment]
Done. For now `rfc3501` will do. It feels like a temporary solution for me. We'll discus [more](https://github.com/duesee/imap-codec/discussions/18).

**Comment by duesee** [comment]
I would like to first squash your commits, then split them again, such that adding `rustfmt.toml` is the first separate commit and the rest the second, and then merge. I don't know how experienced you are with git . Do you prefer to make it yourself or can I do it? (Don't want to take away a learning experience from you :-))

**Comment by duesee** [comment]
Argh, sorry. I had an outdated version...

**Comment by duesee** [comment]
Hey, I merged your commit with a slightly different commit message (f56a20eaaa04720a8a9511fd31f3b127513a53df). Thanks, again! I also worked on the API. You can compile with `cargo doc --all-features` and see what I mean. IMAP extensions were refactored into a new module `extensions` and feature gated with `ext_*` (see `Cargo.toml`). This makes a bit easier to find them. Also, all nom parsers can now be accessed via `internal` and the `nomx` feature. Here, I also unified the documentation a bit.

**Pull request closed without merging**
