### PR TITLE
feat: add `TagGenerator`

### PR DESCRIPTION
**Pull request by duesee**
@jakoschiko 🤬

### CODE REVIEW

**Comment by jakoschiko** [comment]
@duesee How do we handle transitive features? We do re-export `imap-types` in `imap-codec` and `imap-next`. Do we also want to delegate features? Otherwise the benefit of re-exporting `imap-types` (you don't need to specify its version) is lost.

**Comment by duesee** [comment]
Yes, I know :-/ It remembered me this was one of the reasons I thought about removing the re-export. I was too lazy to think more closely how to handle this. Do we want to simply forward all features? Only some? How do we handle name collissions?

**Comment by jakoschiko** [comment]
If we

- re-export `imap-types`
- forward all features
- and suggest not depending directly on `imap-types`

then this

> Also... did you know we can break the build? By using an ext_ feature only in imap-types and not imap-codec?

should be no problem in practice.

**Comment by duesee** [comment]
Yes. I think this is as close as we can get.

**Pull request merged**
