### PR TITLE
Replace `into_owned` with proc macro `ToStatic`.

### LINKED ISSUE #50: Use a more sustainable strategy of implementing `into_owned()`.

### PR DESCRIPTION
**Pull request by jakoschiko**
Resolves #50

### CODE REVIEW

**Comment by duesee** [comment]
Thanks! Could you squash those commits? We can then try to reproduce the error you privately mentioned yesterday.

**Comment by jakoschiko** [comment]
I squashed the commits and rebased the branch. I still get a stack-overflow when running fuzz. Maybe the generated `into_static` has infinite recursion. I'll investigate this.

**Comment by jakoschiko** [comment]
Ok, I finally managed to get a stacktrace with debug symbol (I needed to install llvm-symbolizer). Now the problem is obvious:
```
==91005==ERROR: AddressSanitizer: stack-overflow on address 0x7ffe2dc60d80 (pc 0x55c7e326f749 bp 0x7ffe2dc62830 sp 0x7ffe2dc60d80 T0)
    #0 0x55c7e326f749 in _$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..spec_from_iter_nested..SpecFromIterNested$LT$T$C$I$GT$$GT$::from_iter::h02eafd324cb171c8 (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x50a749) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #1 0x55c7e3331488 in core::iter::adapters::try_process::h6e0602d141f0e5da (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x5cc488) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #2 0x55c7e34766d4 in _$LT$imap_types..rfc3501..body..BodyStructure$u20$as$u20$arbitrary..Arbitrary$GT$::arbitrary::h57da0f369bfd7bfc (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x7116d4) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #3 0x55c7e326fa1a in _$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..spec_from_iter_nested..SpecFromIterNested$LT$T$C$I$GT$$GT$::from_iter::h02eafd324cb171c8 (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x50aa1a) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #4 0x55c7e3331488 in core::iter::adapters::try_process::h6e0602d141f0e5da (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x5cc488) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #5 0x55c7e34766d4 in _$LT$imap_types..rfc3501..body..BodyStructure$u20$as$u20$arbitrary..Arbitrary$GT$::arbitrary::h57da0f369bfd7bfc (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x7116d4) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #6 0x55c7e326fa1a in _$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..spec_from_iter_nested..SpecFromIterNested$LT$T$C$I$GT$$GT$::from_iter::h02eafd324cb171c8 (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x50aa1a) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #7 0x55c7e3331488 in core::iter::adapters::try_process::h6e0602d141f0e5da (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x5cc488) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #8 0x55c7e34766d4 in _$LT$imap_types..rfc3501..body..BodyStructure$u20$as$u20$arbitrary..Arbitrary$GT$::arbitrary::h57da0f369bfd7bfc (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x7116d4) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #9 0x55c7e326fa1a in _$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..spec_from_iter_nested..SpecFromIterNested$LT$T$C$I$GT$$GT$::from_iter::h02eafd324cb171c8 (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x50aa1a) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #10 0x55c7e3331488 in core::iter::adapters::try_process::h6e0602d141f0e5da (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x5cc488) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #11 0x55c7e34766d4 in _$LT$imap_types..rfc3501..body..BodyStructure$u20$as$u20$arbitrary..Arbitrary$GT$::arbitrary::h57da0f369bfd7bfc (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x7116d4) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #12 0x55c7e326fa1a in _$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..spec_from_iter_nested..SpecFromIterNested$LT$T$C$I$GT$$GT$::from_iter::h02eafd324cb171c8 (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x50aa1a) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #13 0x55c7e3331488 in core::iter::adapters::try_process::h6e0602d141f0e5da (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x5cc488) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #14 0x55c7e34766d4 in _$LT$imap_types..rfc3501..body..BodyStructure$u20$as$u20$arbitrary..Arbitrary$GT$::arbitrary::h57da0f369bfd7bfc (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x7116d4) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
    #15 0x55c7e326fa1a in _$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..spec_from_iter_nested..SpecFromIterNested$LT$T$C$I$GT$$GT$::from_iter::h02eafd324cb171c8 (/home/zel/code/rust/imap-codec/target/x86_64-unknown-linux-gnu/release/into_static+0x50aa1a) (BuildId: 78c0a267799a6087051f4e6f65a1ff0511067336)
...
```
`BodyStructure` is a recursive data structure. Hence the derived `Arbitrary` implementation is causing the stack-overflow. Strangely I don't get any stack-overflows on the main branch, only on this branch. So it looks like my changes are causing this problem, but I don't understand how.

**Comment by duesee** [comment]
As discussed privately: Let's merge this. I'll open an issue to fix the `Arbitrary` implementation for body.

**Pull request merged**
